### ISSUE TITLE
struct.error argument out of range for thresholding larger images

### ISSUE THREAD

**Issue by aarony2431** [aarony2431/ImageProcessing#2]
Traceback (most recent call last):
  File "C:\Users\ayu\Documents\Python\pythonProject\ImageProcessing\src\_processimage.py", line 54, in processimages_loop
    processimage(func, imagepath, **kwargs)
  File "C:\Users\ayu\Documents\Python\pythonProject\ImageProcessing\src\_processimage.py", line 41, in processimage
    image.saveRGB(out, newfile, ext='')
  File "C:\Users\ayu\Documents\Python\pythonProject\ImageProcessing\src\_imagetiff.py", line 128, in saveRGB
    self.save(dirpath, name, 'all', ext=ext)
  File "C:\Users\ayu\Documents\Python\pythonProject\ImageProcessing\src\_imagetiff.py", line 117, in save
    Image.fromarray(final_array).save(join(dirpath, name) + ext)
  File "C:\Users\ayu\Miniconda3\envs\pythonProject\lib\site-packages\PIL\Image.py", line 2320, in save
    save_handler(self, fp, filename)
  File "C:\Users\ayu\Miniconda3\envs\pythonProject\lib\site-packages\PIL\TiffImagePlugin.py", line 1831, in _save
    offset = ifd.save(fp)
  File "C:\Users\ayu\Miniconda3\envs\pythonProject\lib\site-packages\PIL\TiffImagePlugin.py", line 931, in save
    result = self.tobytes(offset)
  File "C:\Users\ayu\Miniconda3\envs\pythonProject\lib\site-packages\PIL\TiffImagePlugin.py", line 876, in tobytes
    data = self._write_dispatch[typ](self, *values)
  File "C:\Users\ayu\Miniconda3\envs\pythonProject\lib\site-packages\PIL\TiffImagePlugin.py", line 693, in <lambda>
    b"".join(self._pack(fmt, value) for value in values)
  File "C:\Users\ayu\Miniconda3\envs\pythonProject\lib\site-packages\PIL\TiffImagePlugin.py", line 693, in <genexpr>
    b"".join(self._pack(fmt, value) for value in values)
  File "C:\Users\ayu\Miniconda3\envs\pythonProject\lib\site-packages\PIL\TiffImagePlugin.py", line 660, in _pack
    return struct.pack(self._endian + fmt, *values)
struct.error: argument out of range

**Comment by aarony2431** [comment]
changed image processing to `numpy.memmap` or `tifffile.memmap` or using `tifffile(bigtiff=True)` which accepts BigTIFF files (standard TIFF files are limited in memory to 4GB). Numpy and Tifffile have no cap on the amount of memory and thus are able to access the files and save them with the `bigtiff=True` flag. I used the `memmap` function to transfer data between the original and processed images to the final saved image such that the program minimizes the usage of memory at a single time (see 5395593fe85433809495d1cb93fd355b1144ebca).
